### ISSUE TITLE
Rating stars off position / css broken

### ISSUE THREAD

**Issue by ecleaners** [magesuite/theme-creativeshop#21] opened 2020-06-30 17:27 UTC
It seems the css for the rating stars (cs-reviews__rate-stars) is broken on the pdp - the overlay (filled) stars are in a line below the greyed out versions, and there is a duplicate (gold) stack of 1-5 stars beneath, I hope the screen shows it.

Noticed on the previous version of theme-creativeshop, and it appears to still be persistent in the 8.14.8 release

![rating-stars-pdp](https://user-images.githubusercontent.com/59483252/86157087-28afda80-bb07-11ea-9a72-18670ab974b5.png)

**Comment by mborkowski** [comment] 2021-01-04 11:02
Hi @ecleaners,
Sorry for such a huge delay...
We are not able to reproduce this issue with v10.3.*, therefore I close this issue. Feel free to re-open if this still happens for you

**Closed as completed by mborkowski** 2021-01-04 11:02 UTC
